# Generated by Django 4.2.11 on 2024-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('json_content', models.JSONField(blank=True, help_text='Some json content', null=True, verbose_name='Content')),
            ],
        ),
    ]
